apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtubegaminglive
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: youtubegaminglive
  source:
    repoURL: https://github.com/AndreiTelteu/youtubegaminglive-k8s.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: youtubegaminglive
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
