apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: youtubegaminglive-webhooks
  namespace: argo-events
spec:
  github:
    soketi-webhook:
      owner: "AndreiTelteu"
      repository: "youtubegaminglive-soketi"
      active: true
      contentType: "json"
      webhook:
        port: "12000"
        endpoint: /soketi/github-webhook
        method: POST
      events:
        - "*"
      webhookSecret:
        name: event-youtubegaminglive-soketi-github-secret
        key: secret
    laravel-webhook:
      owner: "AndreiTelteu"
      repository: "YoutubeGamingLive"
      active: true
      contentType: "json"
      webhook:
        port: "12000"
        endpoint: /laravel/github-webhook
        method: POST
      events:
        - "*"
      webhookSecret:
        name: event-youtubegaminglive-laravel-github-secret
        key: secret
    crawler-webhook:
      owner: "AndreiTelteu"
      repository: "youtubegaminglive-crawler"
      active: true
      contentType: "json"
      webhook:
        port: "12000"
        endpoint: /crawler/github-webhook
        method: POST
      events:
        - "*"
      webhookSecret:
        name: event-youtubegaminglive-crawler-github-secret
        key: secret

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: event-youtubegaminglive-soketi-github-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgB3EaUscO8CvvIUdfteT60R3t9qQza6ciFfb7qim1ZOqfST4ia9y7jEQ7E62L0R/r2Wo/su3u2Knt6uCJbImhZ5CdY1IGwirz7FnIE0QgtgNg43z9+g7grTusykZ9NiXwhK9Ncd727fwcrSg1XNE6GuHEvgGdMdvL36xTpSiZdgp6RpI6w7MrAPNQj3ucCSjjU6GKgurB+YF3ORcX86yoJlP+OcdZPARI/SueK0vvyDlmBJhYLarPqyvc+LgayMBkANErNzjo8RlpX4OT0k6COOsqzKt1VkK5NND8YDZliCM8K05KPECeud+7gEJowETTu+tHkEiUChJkEaBwbENk4No3dZxoolUTWPRZINAQSyhfWycc6bz/ReTKK6cErX/nu1ODSkpl8ORtlEiYehwOOxZO5h7TtStoERE2FTjZrsMJ1eF4polcnqZlh0Tutkb3XdcryGEwu6SUhw8X/srO/qJwHPFHVf1dG54IJ3W1Nen/SRxs3DKbBOzTLw0GhhZseU6fVm4eBhyisppme4exuKkLhWPwSJBat19wlOT+9GXNQOe5qmFMI/cM1h97rMVCPhnOjw7+iBs/pgrhCUjBPk5dlHSE80/0zN6bOOTuWzmemjXNnKav0ZtD2qb45/vEwo818TH+Zn1QS95OO0rHJS10eih7Q8JlD7xRC+s8lRhT204qKJLMC9NbexMEy7Vqu4HGVNsfnOlyou6t4agfM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: event-youtubegaminglive-soketi-github-secret
      namespace: argo-events

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: event-youtubegaminglive-laravel-github-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgCVrfRo2jGljCwqpkunkpaqPuixXmdwqpm3RrOyITA+Nxz1+ROW4D4LVS6cc45+EHlAVDjAnvYtsMYVfNCXIq2Q23O1cHHNUhUieLoLecJo3BTgZvF0kuK3YtsA0sUo4/E37khjkAqDmQ9VLPXA2Y5ycpQ1KkvFtuMk+hXkJiaas+JVp8LOkqbsTDBuwhqyR0uq1yg/g+lnmTD3CgF1QQuC+t2sf3jyVSgRtwGpRP8lMMacewKCo4tniIpsWnOR9tMeJgrdH+4PzBGvCrsQ0khZBDGBc08Xtfb3BLQm3IAgqCXSDTPU2pD3in29QHeKmrVtqRaZrLVviVcYn1df88mOb0vCF87nKtsaeNJ3polUSEBM2Xyv7wOyAIdIg0KflymRVpdhpMEH6OojtkhGYHyaO3CWEUmldUWIr7qxAIYilzM/jCFaGP1WxxID7CiKPpmwLwtn6ekjODwqnRMPgmTIsPe/xpmZqLORpzgtNokXbvQiFjP24uodC1S4+mwtWpG2mc+q98VCSKWjJvsAVdOA4gEb3jF78eVpLzRdjW0vrTUijVM0d7XeUjb/enetv8lhTK//BtVPqzni8GtSoAviFNF0pwO133MUjhdNFY591D3yecQ5+nWvkO5JeG7ky/EN6CIuLI47xBC191FMCUms1wgQ5hHlKqpcOk2f58YT8YWCs52KZO1FCv/VV2PkqaBMFDiSNyY7zr4zcvbJOw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: event-youtubegaminglive-laravel-github-secret
      namespace: argo-events

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: event-youtubegaminglive-crawler-github-secret
  namespace: argo-events
spec:
  encryptedData:
    secret: AgCFZR0w390ens/WvRwrUfRonxcciUPieO1TiTiGqEMvPcNJXdKDGMqgPsak+vFogsQ0MkscLgeHOhswdDDyNp1pm0yvgRRwZ1EkZZiqoiCMMNGCLQWqvk5IG3d2mg3UHFuwFksUc9PyLDPDOXceuqWM8CqcxvLAijc114sDWCohJ3lhnfMhqBEGC5Cikizh/sbbV+sGDlxZmX5a0BhzrQoMhNrEa7d/jzSgGFD4p/WJry2WLZZoYWQXyT86nePGwzazdk4Dl1dRriPEVqon/zMMXP+iOdKclsKEXCdBkrtfAKNcxouUt/xkSW8vQidEdijVYuVo1IA2gxDKcKCWEIrxoEBx7E2BHk+aWhcZgQE84tsOlJkYifei1G95uZ7I5I7gUwaCO2ag8K40l4NuFzCFyDpDRaELUjxL+WueFhuQDNsKrZfT3EUP2DGld9XK5M5dAV6iXXCHuF5+p+g746xXB1knxszB/S8q1BdTbNaeRYX5XBBdryhfWVzmcPy6Om6YwSjF3QPCwuwZGFz/c1+Bfja21+8fWB6eQ7Vuu4ydyAOxRySEaLX1v8lIlftJJtIHfb8aw5ufeIuX5/fYoR23uluimfkQg3Rfz2NcsPzPJ7EWboWZO+gorg1w3Vu8aGHY6Ve4jXnNygULg7g3Po/349nfc9F0xgvmKvjBh/uXY0r4l6to2TaA8lF2xmoZjOii8GCVY2wdcs0/b/tIew==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: event-youtubegaminglive-crawler-github-secret
      namespace: argo-events
