apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: crawler
  namespace: youtubegaminglive
spec:
  encryptedData:
    INTERNAL_API_SIG: AgAcrp1HIEsrStMchYmhMZB0AExM0KzxV7LF2MAmwHk6E3VrZb4YlDYtItu6sMw5qjBp7F9FPy8f0tN+QJgXfREpGNiEzpo4ezbSfJpPNSgnH6sQQlvLBFndbhdUBuyEfT3jKmaW1DkRPeROtmF4QH38YlkSEdag3YyBuiFK393jeKWTeBqHV0KuFIpDLg4vc3hfUErOS5APgJkUt2s4KMKGwmUj6SYFMoHFvzFzOdwhVsBqKooNIMj+VQ0TszrZpVOrsrewUGjXl0U3gxYP3DjnI/HeXMh2tlEcYJZrdNmQAvqwpzfjxJRk/32wL5UebUSyqZnGRfZ8yemp1k2A7DtZOr2Ei0f6y23HyNGclIjtdTbpa8hmpEofIYihV8omanefpLZmJjxF6jg0sPZ2fLweM+2KeZyLYLq4VA9k3YaZK35B3J20KZN+5e2FQyeuf4bHornp+7ZjfKkd19EIjNqnBUPezBMeFsZIW20I6kvunOYKEjWZST3dkK1S2cJuHns3k8Ec5+vOFQABDdgPfvN4TlRsg9hobWS4aTlI4WAymLgrrGF3Fo5OYT3ykWbLL2t3J3awmDRWJQikJ+rjZd7AjExmHl7bF43CF1lzflnBibKAo9CGa1knOd5NyPF4uLjHw9Ho65adg5PY6onesvrBx0nEl5J12s+BwOazEv8rR8uHzpxpTBxZFS2ExJjYTevVGNy1JRpyhwZn2vKywQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: crawler
      namespace: youtubegaminglive

