apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: crawler-webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: event-sensor
      eventSourceName: youtubegaminglive-webhooks
      eventName: crawler-webhook
      filters:
        data:
          - path: body.ref
            type: string
            value:
              - "refs/heads/master"
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          parameters:
            - src:
                dependencyName: event-sensor
                dataKey: body.repository.pushed_at
              dest: spec.arguments.parameters.0.value
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: crawler-pipeline-
              spec:
                workflowTemplateRef:
                  name: crawler-pipeline
                entrypoint: release
                arguments:
                  parameters:
                  - name: tag
                    value: '1.0.0'
                podGC:
                  strategy: OnPodCompletion
