apiVersion: v1
kind: Service
metadata:
  name: laravel
  namespace: youtubegaminglive
spec:
  selector:
    app: laravel
  type: ClusterIP
  ports:
  - name: laravel-nginx
    protocol: TCP
    port: 80
    targetPort: 80
